# Generated by Django 4.1 on 2022-08-05 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aivisa_engine', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'verbose_name': 'photo', 'verbose_name_plural': 'photos'},
        ),
        migrations.AddField(
            model_name='photo',
            name='height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='photo',
            name='width',
            field=models.IntegerField(default=0),
        ),
    ]
