# Generated by Django 4.1 on 2022-08-05 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aivisa_engine', '0002_alter_photo_options_photo_height_photo_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='title',
            field=models.TextField(default=''),
        ),
    ]
